language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
matrix:
  include:
    - name: "Python 3.8 on xenial"
      python: '3.8'
      dist: xenial
    - name: "Python 3.8 on bionic"
      python: '3.8'
      dist: bionic
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.7 on macOS"
      python: '3.7'
      os: osx
      osx_image: xcode11.2
      language: minimal
      before_install: sw_vers
    - name: "Python 3.8 on Windows"
      python: '3.8'
      os: windows
      language: bash
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - pytest --cov=source/
after_success: coveralls
